DROP TABLE IF EXISTS logs;

CREATE TABLE logs(
AutoId INT UNSIGNED NOT NULL AUTO_INCREMENT,
LogId INT UNSIGNED NOT NULL DEFAULT 0,
LogType INT UNSIGNED NOT NULL DEFAULT 0,
LogTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
LogKey VARCHAR(4096) NOT NULL DEFAULT '0',
LogMsg VARCHAR(4096) NOT NULL DEFAULT '0',
PRIMARY KEY (`AutoId`) )
ENGINE = MyISAM;
